# Generated by Django 4.1.2 on 2022-10-11 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ourblog", "0003_author_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="author", name="slug",),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to="ourblog.post",
            ),
        ),
    ]
