# Generated by Django 4.1.2 on 2022-10-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ourblog", "0004_remove_author_slug_alter_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
