# Generated by Django 4.1.2 on 2022-10-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ourblog", "0005_comment_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
