# Generated by Django 4.1.2 on 2022-10-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ourblog", "0007_alter_comment_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "permissions": (("can_create_post", "Set to create post"),),
            },
        ),
    ]
