# Generated by Django 4.1.2 on 2022-10-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ourblog", "0012_alter_comment_active_alter_comment_post"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="active",),
    ]
