# Generated by Django 4.1.2 on 2022-10-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ourblog", "0019_alter_author_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "permissions": (("can_create_post", "Set to create post"),),
            },
        ),
    ]
