# Generated by Django 4.1.2 on 2022-10-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ourblog", "0021_alter_post_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
