# Generated by Django 4.1.2 on 2022-10-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ourblog", "0023_alter_comment_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
