# Generated by Django 4.1.2 on 2022-10-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ourblog", "0024_author_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
