# Generated by Django 4.1.2 on 2022-10-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ourblog", "0026_alter_comment_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="created_at", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="post", name="updated_at", field=models.DateTimeField(),
        ),
    ]
