# Generated by Django 4.1.2 on 2022-10-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ourblog", "0027_alter_post_created_at_alter_post_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
